name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Get version
      id: get_version
      run: |
        $version = python main.py --version
        echo "version=$version" >> $env:GITHUB_OUTPUT
        
    - name: Build executable
      run: |
        pyinstaller --onefile --name DoOffice main.py
        
    - name: Create ZIP archive
      run: |
        cd dist
        Compress-Archive -Path DoOffice.exe -DestinationPath "DoOffice_${{ steps.get_version.outputs.version }}_win_x64.zip"
        cd ..
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        release_name: Release ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset (ZIP)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/DoOffice_${{ steps.get_version.outputs.version }}_win_x64.zip
        asset_name: DoOffice_${{ steps.get_version.outputs.version }}_win_x64.zip
        asset_content_type: application/zip
        
    - name: Upload Release Asset (EXE)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/DoOffice.exe
        asset_name: DoOffice.exe
        asset_content_type: application/octet-stream 